Repository wp-cli/package-command, pull requests merged in 2018-08, with the labels that each got.

#87 Adapt package for framework v2
  .travis.yml
  bin/install-package-tests.sh
  bin/test.sh
  composer.json
  features/bootstrap/FeatureContext.php
  features/bootstrap/Process.php
  features/bootstrap/ProcessRun.php
  features/bootstrap/support.php
  features/bootstrap/utils.php
  features/extra/no-mail.php
  features/package-install.feature
  features/package-update.feature
  features/steps/given.php
  features/steps/then.php
  features/steps/when.php
  src/Package_Command.php
  utils/behat-tags.php
Labels: scope:distribution

#88 Add `behat.yml` file for Windows compatibility
  behat.yml
Labels: scope:distribution

#89 Update dependencies
  composer.json
Labels: scope:distribution

#91 Exclude broken Composer version
  composer.json
Labels: scope:distribution

#92 Fix Behat test on Mac OS X (RUN_DIR prefixed with /private)
  features/package-install.feature
Labels: scope:testing

#94 Prefer Packagist over GitHub
  composer.json
  features/package-install.feature
  phpunit.xml.dist
  src/Package_Command.php
  tests/bootstrap.php
  tests/phpunit6-compat.php
  tests/test-composer-json.php
Labels: bug, command:package-install

#95 Show details about out of memory errors, with a link point to the common issue
  src/Package_Command.php
Labels: scope:documentation

#97 Automatically rerun failed scenarios
  .travis.yml
  composer.json
Labels: scope:testing
