Repository wp-cli/package-command, pull requests merged in 2019-04, with the labels that each got.

#105 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#107 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#108 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  package-command.php
  phpcs.xml.dist
  src/Package_Command.php
  tests/test-composer-json.php
Labels: command:package
