Repository wp-cli/package-command, pull requests merged in 2021-05, with the labels that each got.

#133 Move wp-cli/wp-cli-tests to dev dependecies and update
  composer.json
Labels: scope:distribution

#134 Use version range for `wp-cli/wp-cli-tests` dependency
  composer.json
Labels: scope:distribution

#136 Improve installation instructions
  src/Package_Command.php
Labels: scope:documentation

#140 Remove duplicate test and mark remaining as broken
  features/package.feature
Labels: scope:testing
